---
development:
  cloud_name: petrovichscloud
  api_key: '937841794259342'
  api_secret: 5lNfdfst-m-G0pEQAka35zhlxGs
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: petrovichscloud
  api_key: '937841794259342'
  api_secret: 5lNfdfst-m-G0pEQAka35zhlxGs
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: petrovichscloud
  api_key: '937841794259342'
  api_secret: 5lNfdfst-m-G0pEQAka35zhlxGs
  enhance_image_tag: true
  static_image_support: false
